### PR TITLE
Added new Version 5.0.0-qa-18 [Build: 1610541782] Windows

### PR DESCRIPTION
**Pull request by Rikku1338**

### CODE REVIEW

**Comment by Bluscream** [comment]
I think there was an http endpoint to submit versions automatically somewhere

**Comment by Bluscream** [comment]
@Splamy

**Comment by Splamy** [comment]
Chill, I already saw it.
There, I quickly hacked up a frontend for the api: https://splamy.de/TS/Version
Alternatively you can still call the api directly here `POST /api/teamspeak/version/${version}/${platform}?sign=${sign}` (all parameters as normal uri-encoded)

**Comment by Bluscream** [comment]
@Rikku1338 ^ 

Splamy, yes thats what i meant ^^

**Pull request merged**
